-- ============================================================
-- Booking configuration + calendar blocks
-- Run once in Supabase SQL Editor.
--
-- The public booking calendar uses booking_blackouts for exact
-- date/time ranges. The legacy booking_schedule_rules table is no
-- longer read by the website.
-- ============================================================

create table if not exists public.booking_settings (
  id integer primary key default 1 check (id = 1),
  slot_minutes integer not null default 30 check (slot_minutes > 0),
  opening_time time not null default '09:00',
  closing_time time not null default '18:00',
  weekday_slot_minutes integer not null default 30 check (weekday_slot_minutes > 0),
  weekday_opening_time time not null default '09:00',
  weekday_closing_time time not null default '18:00',
  weekend_slot_minutes integer not null default 30 check (weekend_slot_minutes > 0),
  weekend_opening_time time not null default '10:00',
  weekend_closing_time time not null default '16:00',
  advance_months integer not null default 3 check (advance_months > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.booking_blackouts (
  id bigint generated by default as identity primary key,
  starts_at timestamp without time zone not null,
  ends_at timestamp without time zone not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint booking_blackouts_range_chk check (ends_at > starts_at)
);

-- Add the weekday/weekend schedule columns to an existing installation.
-- New columns are added nullable first so an existing custom weekday
-- schedule can be copied from the legacy global fields before NOT NULL
-- constraints/defaults are applied.
alter table if exists public.booking_settings
  add column if not exists weekday_slot_minutes integer,
  add column if not exists weekday_opening_time time,
  add column if not exists weekday_closing_time time,
  add column if not exists weekend_slot_minutes integer,
  add column if not exists weekend_opening_time time,
  add column if not exists weekend_closing_time time;

update public.booking_settings
set
  weekday_slot_minutes = coalesce(weekday_slot_minutes, slot_minutes, 30),
  weekday_opening_time = coalesce(weekday_opening_time, opening_time, '09:00'::time),
  weekday_closing_time = coalesce(weekday_closing_time, closing_time, '18:00'::time),
  weekend_slot_minutes = coalesce(weekend_slot_minutes, 30),
  weekend_opening_time = coalesce(weekend_opening_time, '10:00'::time),
  weekend_closing_time = coalesce(weekend_closing_time, '16:00'::time)
where id = 1;

alter table public.booking_settings
  alter column weekday_slot_minutes set default 30,
  alter column weekday_opening_time set default '09:00',
  alter column weekday_closing_time set default '18:00',
  alter column weekend_slot_minutes set default 30,
  alter column weekend_opening_time set default '10:00',
  alter column weekend_closing_time set default '16:00',
  alter column weekday_slot_minutes set not null,
  alter column weekday_opening_time set not null,
  alter column weekday_closing_time set not null,
  alter column weekend_slot_minutes set not null,
  alter column weekend_opening_time set not null,
  alter column weekend_closing_time set not null;

alter table public.booking_settings
  drop constraint if exists booking_weekday_time_range_chk,
  drop constraint if exists booking_weekend_time_range_chk;

alter table public.booking_settings
  add constraint booking_weekday_time_range_chk
    check (weekday_closing_time > weekday_opening_time),
  add constraint booking_weekend_time_range_chk
    check (weekend_closing_time > weekend_opening_time);

create index if not exists booking_blackouts_start_idx
  on public.booking_blackouts(starts_at);

create index if not exists booking_blackouts_end_idx
  on public.booking_blackouts(ends_at);

-- Keep the legacy table for backwards compatibility with an existing
-- database, but the website and CRM no longer read/write it.
-- It can be dropped later after verifying the new calendar blocks.

create or replace function public.set_booking_settings_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_booking_settings_updated_at
on public.booking_settings;

create trigger trg_booking_settings_updated_at
before update on public.booking_settings
for each row execute function public.set_booking_settings_updated_at();

drop trigger if exists trg_booking_blackouts_updated_at
on public.booking_blackouts;

create trigger trg_booking_blackouts_updated_at
before update on public.booking_blackouts
for each row execute function public.set_booking_settings_updated_at();

-- ============================================================
-- RLS
-- ============================================================

alter table public.booking_settings enable row level security;
alter table public.booking_blackouts enable row level security;

drop policy if exists "public_select_booking_settings"
on public.booking_settings;

create policy "public_select_booking_settings"
on public.booking_settings
for select
to anon, authenticated
using (id = 1);

drop policy if exists "crm_admin_select_booking_settings"
on public.booking_settings;

create policy "crm_admin_select_booking_settings"
on public.booking_settings
for select
to authenticated
using ((select public.is_admin()));

drop policy if exists "crm_admin_insert_booking_settings"
on public.booking_settings;

create policy "crm_admin_insert_booking_settings"
on public.booking_settings
for insert
to authenticated
with check ((select public.is_admin()));

drop policy if exists "crm_admin_update_booking_settings"
on public.booking_settings;

create policy "crm_admin_update_booking_settings"
on public.booking_settings
for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "public_select_booking_blackouts"
on public.booking_blackouts;

create policy "public_select_booking_blackouts"
on public.booking_blackouts
for select
to anon, authenticated
using (true);

drop policy if exists "crm_admin_select_booking_blackouts"
on public.booking_blackouts;

create policy "crm_admin_select_booking_blackouts"
on public.booking_blackouts
for select
to authenticated
using ((select public.is_admin()));

drop policy if exists "crm_admin_insert_booking_blackouts"
on public.booking_blackouts;

create policy "crm_admin_insert_booking_blackouts"
on public.booking_blackouts
for insert
to authenticated
with check ((select public.is_admin()));

drop policy if exists "crm_admin_update_booking_blackouts"
on public.booking_blackouts;

create policy "crm_admin_update_booking_blackouts"
on public.booking_blackouts
for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "crm_admin_delete_booking_blackouts"
on public.booking_blackouts;

create policy "crm_admin_delete_booking_blackouts"
on public.booking_blackouts
for delete
to authenticated
using ((select public.is_admin()));

-- ============================================================
-- Seed booking settings
-- ============================================================

insert into public.booking_settings (
  id,
  slot_minutes,
  opening_time,
  closing_time,
  weekday_slot_minutes,
  weekday_opening_time,
  weekday_closing_time,
  weekend_slot_minutes,
  weekend_opening_time,
  weekend_closing_time,
  advance_months
)
values (
  1,
  30,
  '09:00',
  '18:00',
  30,
  '09:00',
  '18:00',
  30,
  '10:00',
  '16:00',
  3
)
on conflict (id) do update set
  slot_minutes = excluded.slot_minutes,
  opening_time = excluded.opening_time,
  closing_time = excluded.closing_time,
  weekday_slot_minutes = excluded.weekday_slot_minutes,
  weekday_opening_time = excluded.weekday_opening_time,
  weekday_closing_time = excluded.weekday_closing_time,
  weekend_slot_minutes = excluded.weekend_slot_minutes,
  weekend_opening_time = excluded.weekend_opening_time,
  weekend_closing_time = excluded.weekend_closing_time,
  advance_months = excluded.advance_months,
  updated_at = now();

-- ============================================================
-- IMPORTANT:
-- Existing rows in booking_schedule_rules are intentionally NOT
-- applied to the new calendar. Recreate any desired closures or
-- blocked periods in CRM > Booking Setup > Closures & blocked times.
--
-- This avoids silently carrying year-less recurring rules into the
-- new year-aware calendar system.
-- ============================================================

-- Verification:
-- select * from public.booking_settings;
-- select * from public.booking_blackouts order by starts_at;
