-- JAS Premium CRM - Chart of Accounts CRUD + Financial Statements
begin;

-- Ensure finance permissions exist.
insert into public.crm_permissions (section, action, description) values
  ('chart-of-accounts','read','View Chart of Accounts'),
  ('chart-of-accounts','create','Create Chart of Accounts entries'),
  ('chart-of-accounts','update','Update Chart of Accounts entries'),
  ('chart-of-accounts','delete','Delete Chart of Accounts entries'),
  ('financial-statements','read','View Financial Statements')
on conflict (section, action) do nothing;

insert into public.crm_role_permissions (role_id, permission_id)
select r.id,p.id from public.crm_roles r cross join public.crm_permissions p
where lower(r.name)='admin' and p.section in ('chart-of-accounts','financial-statements')
on conflict do nothing;

create table if not exists public.financial_statements (
  id bigint generated by default as identity primary key,
  statement text not null,
  account_code text,
  account_name text,
  classification_line text,
  normal_balance text,
  notes text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists financial_statements_statement_idx on public.financial_statements(statement);
create index if not exists financial_statements_account_code_idx on public.financial_statements(account_code);

create or replace function public.set_financial_statements_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end; $$;
drop trigger if exists financial_statements_set_updated_at on public.financial_statements;
create trigger financial_statements_set_updated_at before update on public.financial_statements for each row execute function public.set_financial_statements_updated_at();

alter table public.financial_statements enable row level security;
drop policy if exists "crm_financial_statements_select" on public.financial_statements;
create policy "crm_financial_statements_select" on public.financial_statements for select to authenticated using (public.crm_has_permission('financial-statements','read'));

-- Make Chart of Accounts CRUD available under the same RLS permission model.
alter table public.chart_of_accounts enable row level security;
drop policy if exists "crm_chart_accounts_select" on public.chart_of_accounts;
drop policy if exists "crm_chart_accounts_insert" on public.chart_of_accounts;
drop policy if exists "crm_chart_accounts_update" on public.chart_of_accounts;
drop policy if exists "crm_chart_accounts_delete" on public.chart_of_accounts;
create policy "crm_chart_accounts_select" on public.chart_of_accounts for select to authenticated using (public.crm_has_permission('chart-of-accounts','read'));
create policy "crm_chart_accounts_insert" on public.chart_of_accounts for insert to authenticated with check (public.crm_has_permission('chart-of-accounts','create'));
create policy "crm_chart_accounts_update" on public.chart_of_accounts for update to authenticated using (public.crm_has_permission('chart-of-accounts','update')) with check (public.crm_has_permission('chart-of-accounts','update'));
create policy "crm_chart_accounts_delete" on public.chart_of_accounts for delete to authenticated using (public.crm_has_permission('chart-of-accounts','delete'));

insert into public.financial_statements (statement,account_code,account_name,classification_line,normal_balance,notes)
select v.statement,v.account_code,v.account_name,v.classification_line,v.normal_balance,v.notes
from (values
('Balance Sheet','1100-1660','Cash, Bank, Receivables, Inventory, Prepayments & Fixed Assets','ASSETS','Debit','Use detailed accounts from Sheet 1'),
('Balance Sheet','1690-1694','Accumulated Depreciation','Less: Accumulated Depreciation','Credit',null),
('Balance Sheet','2100-2500','Accounts Payable, Accruals, Customer Advances & Other Current Liabilities','CURRENT LIABILITIES','Credit',null),
('Balance Sheet','2610','Bank Loan - Current Portion','Current Borrowings','Credit',null),
('Balance Sheet','2710','Lease Liability - Current','Current Lease Liability','Credit','If IFRS 16 applies'),
('Balance Sheet','2620','Bank Loan - Long Term','NON-CURRENT LIABILITIES','Credit',null),
('Balance Sheet','2720','Lease Liability - Non-current','Non-current Lease Liability','Credit','If IFRS 16 applies'),
('Balance Sheet','3100-3600','Share Capital, Additional Paid-in Capital, Retained Earnings & Current Year Profit/Loss','EQUITY','Credit/Debit',null),
('Profit & Loss','4100-4500','Hair, Beauty, Package/Membership & Retail Sales Revenue','REVENUE','Credit',null),
('Profit & Loss','4900','Sales Discounts & Allowances','Less: Discounts','Debit',null),
('Profit & Loss','5100-5400','Hair Products, Beauty Consumables & Retail Product Costs','COST OF SALES','Debit',null),
('Profit & Loss',null,'Gross Profit','Revenue - Discounts - Cost of Sales','Credit','Calculated subtotal'),
('Profit & Loss','6100-7700','Salaries, Rent, Utilities, Marketing, Bank Fees, Depreciation & Other Operating Costs','OPERATING EXPENSES','Debit',null),
('Profit & Loss',null,'Operating Profit / (Loss)','Gross Profit - Operating Expenses','Credit/Debit','Calculated subtotal'),
('Profit & Loss','8100','Interest Income','Other Income','Credit',null),
('Profit & Loss','8200, 8400, 8500, 8600','Interest, FX, Tax & Asset Disposal Items','Other / Finance / Tax','Debit/Credit',null),
('Profit & Loss',null,'Net Profit / (Loss)','Final Profit or Loss','Credit/Debit','Transfers to equity at year-end'),
('Trial Balance','1000-8600','All active ledger accounts','Debit and Credit Columns','Debit/Credit','Every general ledger account appears here before closing entries'),
('Trial Balance',null,'Total Debits','Must equal Total Credits','Debit','Control total'),
('Trial Balance',null,'Total Credits','Must equal Total Debits','Credit','Control total'),
('Cash Flow','1100-1220','Cash and Bank','Cash & Cash Equivalents','Debit',null),
('Cash Flow','4100-4500','Salon Service & Retail Collections','Cash Flows from Operating Activities','Credit','Adjusted for receivables/customer advances'),
('Cash Flow','5100-7700','Payments to Suppliers, Employees, Rent, Utilities & Other Operating Expenses','Cash Flows from Operating Activities','Debit',null),
('Cash Flow','1600-1660','Purchase of Equipment, Furniture, Fit-out & Other Fixed Assets','Cash Flows from Investing Activities','Debit',null),
('Cash Flow','8600','Proceeds from / loss on disposal of assets','Cash Flows from Investing Activities','Debit/Credit',null),
('Cash Flow','2600-2720','Loans, Repayments & Lease Payments','Cash Flows from Financing Activities','Debit/Credit',null),
('Cash Flow','3100-3600','Capital Contributions & Owner/Shareholder Distributions','Cash Flows from Financing Activities','Debit/Credit',null),
('Statement of Changes in Equity','3100','Share Capital','Opening Balance + Capital Contributions','Credit',null),
('Statement of Changes in Equity','3200','Additional Paid-in Capital','Additional Contributions','Credit',null),
('Statement of Changes in Equity','3400','Retained Earnings','Opening Retained Earnings + Prior Period Results','Credit',null),
('Statement of Changes in Equity','3500','Current Year Profit / Loss','Profit / Loss for the Year','Credit/Debit',null),
('Statement of Changes in Equity','3600','Dividends / Drawings','Less: Distributions','Debit',null),
('Statement of Changes in Equity',null,'Closing Equity','Opening Equity + Contributions + Profit/Loss - Distributions','Credit/Debit',null)
) as v(statement,account_code,account_name,classification_line,normal_balance,notes)
where not exists (
  select 1 from public.financial_statements f
  where f.statement=v.statement
    and coalesce(f.account_code,'')=coalesce(v.account_code,'')
    and coalesce(f.account_name,'')=coalesce(v.account_name,'')
    and coalesce(f.classification_line,'')=coalesce(v.classification_line,'')
    and coalesce(f.normal_balance,'')=coalesce(v.normal_balance,'')
);
commit;
