-- ============================================================
-- Contact Us messages
-- ============================================================
-- Run once in the SQL editor after the CRM role/permission system exists.

begin;

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  status text not null default 'new'
    check (status in ('new','contacted')),
  created_at timestamptz not null default now()
);

alter table public.contact_messages enable row level security;

drop policy if exists contact_messages_public_insert on public.contact_messages;
create policy contact_messages_public_insert
on public.contact_messages
for insert
to anon, authenticated
with check (
  nullif(trim(name), '') is not null
  and nullif(trim(phone), '') is not null
);

drop policy if exists contact_messages_crm_read on public.contact_messages;
create policy contact_messages_crm_read
on public.contact_messages
for select
to authenticated
using (public.crm_has_permission('contact-messages','read'));

drop policy if exists contact_messages_crm_update on public.contact_messages;
create policy contact_messages_crm_update
on public.contact_messages
for update
to authenticated
using (public.crm_has_permission('contact-messages','update'))
with check (public.crm_has_permission('contact-messages','update'));

drop policy if exists contact_messages_crm_delete on public.contact_messages;
create policy contact_messages_crm_delete
on public.contact_messages
for delete
to authenticated
using (public.crm_has_permission('contact-messages','delete'));

insert into public.crm_permissions (section, action, description)
values
  ('contact-messages','read','View Contact Us requests'),
  ('contact-messages','create','Create Contact Us requests'),
  ('contact-messages','update','Update Contact Us requests'),
  ('contact-messages','delete','Delete Contact Us requests')
on conflict (section, action) do nothing;

-- Administrators receive all Contact Us permissions.
insert into public.crm_role_permissions (role_id, permission_id)
select r.id, p.id
from public.crm_roles r
cross join public.crm_permissions p
where lower(r.name) in ('admin','administrator')
  and p.section = 'contact-messages'
on conflict do nothing;

commit;
