-- ============================================================
-- FAQ catalogue in Supabase
-- Replaces assets/data/faq.json.
-- Run once in the Supabase SQL Editor.
-- ============================================================

create table if not exists public.faq_settings (
  id integer primary key default 1 check (id = 1),
  title_en text not null,
  title_ar text,
  description_en text,
  description_ar text,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.faqs (
  id bigint generated by default as identity primary key,
  question_en text not null,
  question_ar text,
  answer_en text not null,
  answer_ar text,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists faqs_active_sort_idx
  on public.faqs(active, sort_order, id);

create or replace function public.set_faq_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_faqs_updated_at on public.faqs;
create trigger trg_faqs_updated_at
before update on public.faqs
for each row execute function public.set_faq_updated_at();

create or replace function public.set_faq_settings_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_faq_settings_updated_at on public.faq_settings;
create trigger trg_faq_settings_updated_at
before update on public.faq_settings
for each row execute function public.set_faq_settings_updated_at();

-- Public website may read the active FAQ content.
alter table public.faq_settings enable row level security;
alter table public.faqs enable row level security;

drop policy if exists "public_select_active_faq_settings" on public.faq_settings;
create policy "public_select_active_faq_settings"
on public.faq_settings
for select
to anon, authenticated
using (active = true);

drop policy if exists "public_select_active_faqs" on public.faqs;
create policy "public_select_active_faqs"
on public.faqs
for select
to anon, authenticated
using (active = true);

-- CRM admins may manage FAQ content.
drop policy if exists "crm_admin_select_faq_settings" on public.faq_settings;
create policy "crm_admin_select_faq_settings"
on public.faq_settings
for select
to authenticated
using ((select public.is_admin()));

drop policy if exists "crm_admin_insert_faq_settings" on public.faq_settings;
create policy "crm_admin_insert_faq_settings"
on public.faq_settings
for insert
to authenticated
with check ((select public.is_admin()));

drop policy if exists "crm_admin_update_faq_settings" on public.faq_settings;
create policy "crm_admin_update_faq_settings"
on public.faq_settings
for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "crm_admin_delete_faq_settings" on public.faq_settings;
create policy "crm_admin_delete_faq_settings"
on public.faq_settings
for delete
to authenticated
using ((select public.is_admin()));

drop policy if exists "crm_admin_select_faqs" on public.faqs;
create policy "crm_admin_select_faqs"
on public.faqs
for select
to authenticated
using ((select public.is_admin()));

drop policy if exists "crm_admin_insert_faqs" on public.faqs;
create policy "crm_admin_insert_faqs"
on public.faqs
for insert
to authenticated
with check ((select public.is_admin()));

drop policy if exists "crm_admin_update_faqs" on public.faqs;
create policy "crm_admin_update_faqs"
on public.faqs
for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "crm_admin_delete_faqs" on public.faqs;
create policy "crm_admin_delete_faqs"
on public.faqs
for delete
to authenticated
using ((select public.is_admin()));

-- Seed settings.
insert into public.faq_settings
  (id, title_en, title_ar, description_en, description_ar, active)
values
  (
    1,
    'FAQ',
    'الأسئلة الشائعة',
    'If you have any questions regarding the services our barbershop offers, feel free to browse this section of frequently asked questions.',
    'إذا كانت لديك أي أسئلة بخصوص الخدمات التي يقدمها صالون الحلاقة لدينا، يمكنك تصفح قسم الأسئلة الشائعة.',
    true
  )
on conflict (id) do update
set
  title_en = excluded.title_en,
  title_ar = excluded.title_ar,
  description_en = excluded.description_en,
  description_ar = excluded.description_ar,
  active = excluded.active,
  updated_at = now();

-- Seed the existing FAQ items.
insert into public.faqs
  (question_en, question_ar, answer_en, answer_ar, active, sort_order)
select *
from (
  values
    (
      'Is it OK if I am a few minutes late for my appointment?',
      'هل يمكن أن أتأخر بضع دقائق عن موعدي؟',
      'We schedule clients on the half-hour and we make full use of those 30 minutes with each client. If someone is 5 minutes late for their appointment, it affects every client after them, as well as the barber who is trying to stay on schedule...',
      'نحن نحدد المواعيد على نصف الساعة ونستفيد من كامل الثلاثين دقيقة مع كل زبون. إذا تأخر أحدهم خمس دقائق عن موعده، فإن ذلك يؤثر على جميع العملاء بعده وكذلك على الحلاق الذي يحاول الالتزام بالجدول...',
      true,
      1
    ),
    (
      'What is your appointment policy?',
      'ما هي سياسة المواعيد لديكم؟',
      'If you need to cancel your appointment, please do so as far in advance as possible, preferably at least one hour. Our appointment policy is listed on the appointment page.',
      'إذا كنت بحاجة إلى إلغاء موعدك، يرجى القيام بذلك في أقرب وقت ممكن، ويفضل قبل ساعة على الأقل. سياسة المواعيد لدينا مذكورة في صفحة المواعيد.',
      true,
      2
    ),
    (
      'When do you take your last walk-in?',
      'متى تستقبلون آخر زبون بدون موعد؟',
      'Our walk-in list closes when there are as many customers waiting as we can serve before closing time. It may reopen if customers leave the line...',
      'تُغلق قائمة الزبائن بدون موعد عندما يكون هناك عدد من العملاء المنتظرين بقدر ما يمكننا خدمته قبل وقت الإغلاق. قد يُعاد فتحها إذا غادر بعض العملاء الطابور...',
      true,
      3
    )
) as seed(question_en, question_ar, answer_en, answer_ar, active, sort_order)
where not exists (
  select 1 from public.faqs
);

-- Verify:
-- select * from public.faq_settings;
-- select id, question_en, active, sort_order from public.faqs order by sort_order, id;
