
-- ============================================================
-- JAS PREMIUM FINANCE AREA
-- Chart of Accounts + Journal Entries + General Ledger +
-- Trial Balance + Financial Statement Mapping + Periods
-- All finance data is stored in Supabase.
-- ============================================================
begin;

-- Finance permissions
insert into public.crm_permissions (section, action, description) values
 ('journal-entries','read','View journal entries'),
 ('journal-entries','create','Create journal entries'),
 ('journal-entries','update','Edit draft journal entries'),
 ('journal-entries','delete','Delete draft journal entries'),
 ('journal-entries','post','Post journal entries'),
 ('general-ledger','read','View general ledger'),
 ('trial-balance','read','View trial balance'),
 ('statement-mapping','read','View financial statement mappings'),
 ('statement-mapping','create','Create financial statement mappings'),
 ('statement-mapping','update','Edit financial statement mappings'),
 ('statement-mapping','delete','Delete financial statement mappings'),
 ('accounting-periods','read','View accounting periods'),
 ('accounting-periods','create','Create accounting periods'),
 ('accounting-periods','update','Edit accounting periods'),
 ('accounting-periods','delete','Delete accounting periods')
on conflict(section,action) do update set description=excluded.description;

-- Administrators get all finance permissions.
insert into public.crm_role_permissions(role_id,permission_id)
select r.id,p.id
from public.crm_roles r cross join public.crm_permissions p
where lower(r.name) in ('admin','administrator')
and p.section in ('journal-entries','general-ledger','trial-balance','statement-mapping','accounting-periods')
on conflict do nothing;

-- Accounting periods
create table if not exists public.accounting_periods (
 id bigint generated by default as identity primary key,
 name text not null,
 start_date date not null,
 end_date date not null,
 status text not null default 'open' check(status in ('open','closed')),
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 constraint accounting_periods_dates_check check(end_date >= start_date)
);
create unique index if not exists accounting_periods_date_unique on public.accounting_periods(start_date,end_date);

-- Journal header
create table if not exists public.journal_entries (
 id bigint generated by default as identity primary key,
 entry_no text unique,
 entry_date date not null default current_date,
 reference text,
 description text not null,
 status text not null default 'draft' check(status in ('draft','posted','void')),
 total_debit numeric(14,2) not null default 0,
 total_credit numeric(14,2) not null default 0,
 created_by uuid references auth.users(id),
 posted_by uuid references auth.users(id),
 posted_at timestamptz,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
create index if not exists journal_entries_date_idx on public.journal_entries(entry_date);
create index if not exists journal_entries_status_idx on public.journal_entries(status);

-- Journal lines
create table if not exists public.journal_entry_lines (
 id bigint generated by default as identity primary key,
 journal_entry_id bigint not null references public.journal_entries(id) on delete cascade,
 line_no integer not null,
 account_code text not null references public.chart_of_accounts(account_code),
 description text,
 debit numeric(14,2) not null default 0 check(debit >= 0),
 credit numeric(14,2) not null default 0 check(credit >= 0),
 created_at timestamptz not null default now(),
 constraint journal_line_one_side check(not(debit > 0 and credit > 0)),
 constraint journal_line_amount check(debit > 0 or credit > 0),
 unique(journal_entry_id,line_no)
);
create index if not exists journal_lines_account_idx on public.journal_entry_lines(account_code);
create index if not exists journal_lines_entry_idx on public.journal_entry_lines(journal_entry_id);

-- Statement mapping is intentionally separate from the report output.
create table if not exists public.financial_statement_mappings (
 id bigint generated by default as identity primary key,
 statement text not null check(statement in ('Balance Sheet','Profit & Loss','Cash Flow','Statement of Changes in Equity')),
 account_code text not null references public.chart_of_accounts(account_code),
 section_line text not null,
 display_order integer not null default 1,
 active boolean not null default true,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
create index if not exists fsm_statement_order_idx on public.financial_statement_mappings(statement,display_order);
create unique index if not exists fsm_account_statement_unique on public.financial_statement_mappings(statement,account_code);

-- Generate JE numbers from the database identity, so they are unique.
create or replace function public.set_journal_entry_no()
returns trigger language plpgsql as $$
begin
  if new.entry_no is null or btrim(new.entry_no)='' then
    new.entry_no := 'JE-' || lpad(new.id::text,6,'0');
  end if;
  return new;
end $$;
drop trigger if exists journal_entry_no_trigger on public.journal_entries;
create trigger journal_entry_no_trigger before insert on public.journal_entries
for each row execute function public.set_journal_entry_no();

-- Keep header totals synchronized from lines.
create or replace function public.refresh_journal_entry_totals(p_entry_id bigint)
returns void language sql as $$
 update public.journal_entries j
 set total_debit=coalesce((select sum(debit) from public.journal_entry_lines where journal_entry_id=p_entry_id),0),
     total_credit=coalesce((select sum(credit) from public.journal_entry_lines where journal_entry_id=p_entry_id),0),
     updated_at=now()
 where j.id=p_entry_id;
$$;

create or replace function public.refresh_journal_totals_trigger()
returns trigger language plpgsql as $$
begin
  perform public.refresh_journal_entry_totals(coalesce(new.journal_entry_id,old.journal_entry_id));
  return coalesce(new,old);
end $$;
drop trigger if exists journal_lines_totals_trigger on public.journal_entry_lines;
create trigger journal_lines_totals_trigger after insert or update or delete on public.journal_entry_lines
for each row execute function public.refresh_journal_totals_trigger();

-- Posting is atomic and validates balance + period.
create or replace function public.post_journal_entry(p_entry_id bigint)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare j public.journal_entries%rowtype;
declare d numeric(14,2); c numeric(14,2);
declare period_status text;
begin
 if not public.crm_has_permission('journal-entries','post') then
   raise exception 'You do not have permission to post journal entries.';
 end if;
 select * into j from public.journal_entries where id=p_entry_id for update;
 if not found then raise exception 'Journal entry not found.'; end if;
 if j.status <> 'draft' then raise exception 'Only draft journal entries can be posted.'; end if;
 select coalesce(sum(debit),0),coalesce(sum(credit),0) into d,c from public.journal_entry_lines where journal_entry_id=p_entry_id;
 if d <= 0 or abs(d-c)>0.005 then raise exception 'Journal entry is not balanced.'; end if;
 if exists(select 1 from public.accounting_periods ap where j.entry_date between ap.start_date and ap.end_date and ap.status='closed') then
   raise exception 'The accounting period for this date is closed.';
 end if;
 if not exists(select 1 from public.journal_entry_lines where journal_entry_id=p_entry_id having count(*) >= 2) then
   raise exception 'A journal entry needs at least two lines.';
 end if;
 update public.journal_entries set status='posted',total_debit=d,total_credit=c,posted_by=auth.uid(),posted_at=now(),updated_at=now() where id=p_entry_id;
 return jsonb_build_object('id',p_entry_id,'status','posted');
end $$;
grant execute on function public.post_journal_entry(bigint) to authenticated;

-- RLS
alter table public.accounting_periods enable row level security;
alter table public.journal_entries enable row level security;
alter table public.journal_entry_lines enable row level security;
alter table public.financial_statement_mappings enable row level security;

drop policy if exists finance_period_read on public.accounting_periods;
drop policy if exists finance_period_create on public.accounting_periods;
drop policy if exists finance_period_update on public.accounting_periods;
drop policy if exists finance_period_delete on public.accounting_periods;
create policy finance_period_read on public.accounting_periods for select to authenticated using(public.crm_has_permission('accounting-periods','read'));
create policy finance_period_create on public.accounting_periods for insert to authenticated with check(public.crm_has_permission('accounting-periods','create'));
create policy finance_period_update on public.accounting_periods for update to authenticated using(public.crm_has_permission('accounting-periods','update')) with check(public.crm_has_permission('accounting-periods','update'));
create policy finance_period_delete on public.accounting_periods for delete to authenticated using(public.crm_has_permission('accounting-periods','delete'));

drop policy if exists finance_journal_read on public.journal_entries;
drop policy if exists finance_journal_create on public.journal_entries;
drop policy if exists finance_journal_update on public.journal_entries;
drop policy if exists finance_journal_delete on public.journal_entries;
create policy finance_journal_read on public.journal_entries for select to authenticated using(public.crm_has_permission('journal-entries','read'));
create policy finance_journal_create on public.journal_entries for insert to authenticated with check(public.crm_has_permission('journal-entries','create'));
create policy finance_journal_update on public.journal_entries for update to authenticated using(public.crm_has_permission('journal-entries','update') and status='draft') with check(public.crm_has_permission('journal-entries','update') and status='draft');
create policy finance_journal_delete on public.journal_entries for delete to authenticated using(public.crm_has_permission('journal-entries','delete') and status='draft');

drop policy if exists finance_lines_read on public.journal_entry_lines;
drop policy if exists finance_lines_create on public.journal_entry_lines;
drop policy if exists finance_lines_update on public.journal_entry_lines;
drop policy if exists finance_lines_delete on public.journal_entry_lines;
create policy finance_lines_read on public.journal_entry_lines for select to authenticated using(public.crm_has_permission('journal-entries','read'));
create policy finance_lines_create on public.journal_entry_lines for insert to authenticated with check(public.crm_has_permission('journal-entries','create'));
create policy finance_lines_update on public.journal_entry_lines for update to authenticated using(public.crm_has_permission('journal-entries','update'));
create policy finance_lines_delete on public.journal_entry_lines for delete to authenticated using(public.crm_has_permission('journal-entries','update'));

drop policy if exists finance_mapping_read on public.financial_statement_mappings;
drop policy if exists finance_mapping_create on public.financial_statement_mappings;
drop policy if exists finance_mapping_update on public.financial_statement_mappings;
drop policy if exists finance_mapping_delete on public.financial_statement_mappings;
create policy finance_mapping_read on public.financial_statement_mappings for select to authenticated using(public.crm_has_permission('statement-mapping','read'));
create policy finance_mapping_create on public.financial_statement_mappings for insert to authenticated with check(public.crm_has_permission('statement-mapping','create'));
create policy finance_mapping_update on public.financial_statement_mappings for update to authenticated using(public.crm_has_permission('statement-mapping','update')) with check(public.crm_has_permission('statement-mapping','update'));
create policy finance_mapping_delete on public.financial_statement_mappings for delete to authenticated using(public.crm_has_permission('statement-mapping','delete'));

-- Seed mappings from the existing Excel-imported financial_statements table.
insert into public.financial_statement_mappings(statement,account_code,section_line,display_order,active)
select f.statement,f.account_code,coalesce(nullif(f.classification_line,''),f.account_name),row_number() over(partition by f.statement order by f.account_code),coalesce(f.active,true)
from public.financial_statements f
where f.account_code is not null and exists(select 1 from public.chart_of_accounts c where c.account_code=f.account_code)
on conflict(statement,account_code) do update
set section_line=excluded.section_line, display_order=excluded.display_order, active=excluded.active;

commit;
