-- ============================================================
-- JAS PREMIUM FINANCE AUDIT TRAIL + ACCOUNTANT EXPORT LOGGING
-- Run after FINANCE-AREA-SETUP.sql
-- ============================================================
begin;

insert into public.crm_permissions(section,action,description) values
 ('audit-trail','read','View finance audit trail')
on conflict(section,action) do update set description=excluded.description;

insert into public.crm_role_permissions(role_id,permission_id)
select r.id,p.id
from public.crm_roles r cross join public.crm_permissions p
where lower(r.name) in ('admin','administrator')
  and p.section='audit-trail' and p.action='read'
on conflict do nothing;

create table if not exists public.finance_audit_trail (
 id bigint generated by default as identity primary key,
 created_at timestamptz not null default now(),
 actor_id uuid references auth.users(id),
 actor_email text,
 action text not null,
 table_name text,
 record_id text,
 details jsonb not null default '{}'::jsonb
);
create index if not exists finance_audit_created_idx on public.finance_audit_trail(created_at desc);
create index if not exists finance_audit_table_record_idx on public.finance_audit_trail(table_name,record_id);
create index if not exists finance_audit_action_idx on public.finance_audit_trail(action);

alter table public.finance_audit_trail enable row level security;
drop policy if exists finance_audit_read on public.finance_audit_trail;
create policy finance_audit_read on public.finance_audit_trail
for select to authenticated
using(public.crm_has_permission('audit-trail','read'));

-- Only the database writes audit rows. Clients cannot update or delete history.
revoke insert, update, delete on public.finance_audit_trail from anon,authenticated;
grant select on public.finance_audit_trail to authenticated;

create or replace function public.finance_audit_trigger()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare
  row_data jsonb;
  old_data jsonb;
  rec_id text;
  actor uuid := auth.uid();
  actor_mail text := coalesce(auth.jwt()->>'email','');
  audit_action text;
begin
  if tg_op='INSERT' then
    row_data := to_jsonb(new);
    old_data := null;
    rec_id := row_data->>'id';
    audit_action := 'CREATE';
  elsif tg_op='UPDATE' then
    row_data := to_jsonb(new);
    old_data := to_jsonb(old);
    rec_id := row_data->>'id';
    audit_action := 'UPDATE';
  else
    row_data := null;
    old_data := to_jsonb(old);
    rec_id := old_data->>'id';
    audit_action := 'DELETE';
  end if;

  insert into public.finance_audit_trail(actor_id,actor_email,action,table_name,record_id,details)
  values(
    actor,
    nullif(actor_mail,''),
    audit_action,
    tg_table_name,
    rec_id,
    jsonb_build_object('old',old_data,'new',row_data)
  );
  return coalesce(new,old);
end $$;

-- Journal headers: create, edit drafts, post, and delete.
drop trigger if exists finance_audit_journal_entries on public.journal_entries;
create trigger finance_audit_journal_entries
after insert or update or delete on public.journal_entries
for each row execute function public.finance_audit_trigger();

-- Journal lines: keep the underlying debit/credit changes auditable too.
drop trigger if exists finance_audit_journal_lines on public.journal_entry_lines;
create trigger finance_audit_journal_lines
after insert or update or delete on public.journal_entry_lines
for each row execute function public.finance_audit_trigger();

-- Statement mappings and accounting periods affect reported results and must be traceable.
drop trigger if exists finance_audit_statement_mappings on public.financial_statement_mappings;
create trigger finance_audit_statement_mappings
after insert or update or delete on public.financial_statement_mappings
for each row execute function public.finance_audit_trigger();

drop trigger if exists finance_audit_accounting_periods on public.accounting_periods;
create trigger finance_audit_accounting_periods
after insert or update or delete on public.accounting_periods
for each row execute function public.finance_audit_trigger();

-- Chart of Accounts changes can alter reporting classifications, so audit them too.
drop trigger if exists finance_audit_chart_of_accounts on public.chart_of_accounts;
create trigger finance_audit_chart_of_accounts
after insert or update or delete on public.chart_of_accounts
for each row execute function public.finance_audit_trigger();

-- Used by the CRM when an accountant exports/prints a report. The RPC validates
-- the action/table combination and records the current authenticated user.
create or replace function public.log_finance_audit(
  p_action text,
  p_table_name text,
  p_record_id text default null,
  p_details jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path=public
as $$
declare
  allowed boolean := false;
  audit_id bigint;
begin
  if p_action in ('EXPORT_CSV','PRINT_PDF') then
    allowed := p_table_name in ('journal_entries','general_ledger','trial_balance','financial_statements','finance_audit_trail')
      and (
        public.crm_has_permission('audit-trail','read')
        or (p_table_name='journal_entries' and public.crm_has_permission('journal-entries','read'))
        or (p_table_name='general_ledger' and public.crm_has_permission('general-ledger','read'))
        or (p_table_name='trial_balance' and public.crm_has_permission('trial-balance','read'))
        or (p_table_name='financial_statements' and public.crm_has_permission('financial-statements','read'))
      );
  end if;
  if not allowed then raise exception 'You do not have permission to record this finance action.'; end if;

  insert into public.finance_audit_trail(actor_id,actor_email,action,table_name,record_id,details)
  values(auth.uid(),nullif(auth.jwt()->>'email',''),p_action,p_table_name,p_record_id,coalesce(p_details,'{}'::jsonb))
  returning id into audit_id;
  return audit_id;
end $$;

grant execute on function public.log_finance_audit(text,text,text,jsonb) to authenticated;

-- Populate created_by on journal headers for future records.
create or replace function public.set_journal_created_by()
returns trigger language plpgsql as $$
begin
  if new.created_by is null then new.created_by := auth.uid(); end if;
  return new;
end $$;
drop trigger if exists journal_created_by_trigger on public.journal_entries;
create trigger journal_created_by_trigger before insert on public.journal_entries
for each row execute function public.set_journal_created_by();

commit;
-- URL QR destinations are operational records too: changing a destination
-- must be auditable while the permanent QR identity remains unchanged.
drop trigger if exists finance_audit_url_qr_codes on public.url_qr_codes;
create trigger finance_audit_url_qr_codes
after insert or update or delete on public.url_qr_codes
for each row execute function public.finance_audit_trigger();

