-- ============================================================
-- CRM CUSTOMER LOYALTY & REWARDS
-- Points are earned automatically when a booking is marked completed.
-- Staff can also add/remove points and redeem rewards from the CRM.
-- ============================================================

alter table public.customers
  add column if not exists loyalty_points integer not null default 0,
  add column if not exists loyalty_lifetime_points integer not null default 0,
  add column if not exists loyalty_tier text not null default 'Member';

alter table public.customers
  drop constraint if exists customers_loyalty_points_check;
alter table public.customers
  add constraint customers_loyalty_points_check check (loyalty_points >= 0 and loyalty_lifetime_points >= 0);

create table if not exists public.customer_loyalty_transactions (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id) on delete cascade,
  points integer not null check (points <> 0),
  transaction_type text not null check (transaction_type in ('booking_earned','manual_adjustment','reward_redeemed')),
  description text not null,
  source_booking_id text unique,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists customer_loyalty_transactions_customer_idx
  on public.customer_loyalty_transactions(customer_id, created_at desc);

alter table public.customer_loyalty_transactions enable row level security;
drop policy if exists "crm_admin_select_loyalty_transactions" on public.customer_loyalty_transactions;
drop policy if exists "crm_admin_insert_loyalty_transactions" on public.customer_loyalty_transactions;
create policy "crm_admin_select_loyalty_transactions"
on public.customer_loyalty_transactions for select to authenticated
using (public.is_admin());
create policy "crm_admin_insert_loyalty_transactions"
on public.customer_loyalty_transactions for insert to authenticated
with check (public.is_admin());

create or replace function public.crm_loyalty_tier(p_lifetime integer)
returns text
language sql immutable
as $$
  select case
    when coalesce(p_lifetime,0) >= 600 then 'Platinum'
    when coalesce(p_lifetime,0) >= 300 then 'Gold'
    when coalesce(p_lifetime,0) >= 100 then 'Silver'
    else 'Member'
  end;
$$;

create or replace function public.crm_adjust_customer_loyalty(
  p_customer_id bigint,
  p_points integer,
  p_description text,
  p_transaction_type text default 'manual_adjustment'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_customer public.customers%rowtype;
  v_new_balance integer;
  v_new_lifetime integer;
  v_type text := coalesce(p_transaction_type,'manual_adjustment');
begin
  if not public.crm_has_permission('customers','update') then
    raise exception 'Not authorized to update customer loyalty';
  end if;
  if p_points = 0 then raise exception 'Points change cannot be zero'; end if;
  if v_type not in ('manual_adjustment','reward_redeemed') then raise exception 'Invalid loyalty transaction type'; end if;
  if nullif(trim(coalesce(p_description,'')),'') is null then raise exception 'A loyalty transaction description is required'; end if;

  select * into v_customer from public.customers where id = p_customer_id and coalesce(is_deleted,false) = false for update;
  if not found then raise exception 'Customer not found'; end if;

  v_new_balance := coalesce(v_customer.loyalty_points,0) + p_points;
  if v_new_balance < 0 then raise exception 'Customer does not have enough loyalty points'; end if;
  v_new_lifetime := greatest(coalesce(v_customer.loyalty_lifetime_points,0), coalesce(v_customer.loyalty_lifetime_points,0) + greatest(p_points,0));

  update public.customers
  set loyalty_points = v_new_balance,
      loyalty_lifetime_points = v_new_lifetime,
      loyalty_tier = public.crm_loyalty_tier(v_new_lifetime)
  where id = p_customer_id;

  insert into public.customer_loyalty_transactions(customer_id,points,transaction_type,description,created_by)
  values (p_customer_id,p_points,v_type,trim(p_description),auth.uid());

  return jsonb_build_object(
    'customer_id', p_customer_id,
    'points', v_new_balance,
    'lifetime_points', v_new_lifetime,
    'tier', public.crm_loyalty_tier(v_new_lifetime)
  );
end;
$$;

revoke all on function public.crm_adjust_customer_loyalty(bigint,integer,text,text) from public;
grant execute on function public.crm_adjust_customer_loyalty(bigint,integer,text,text) to authenticated;

create or replace function public.crm_award_booking_loyalty()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_points integer;
  v_lifetime integer;
begin
  if lower(coalesce(new.status,'')) <> 'completed' or new.customer_id is null then
    return new;
  end if;

  v_points := greatest(0, floor(coalesce(new.total_price,0))::integer);
  if v_points <= 0 then return new; end if;

  if not exists (
    select 1 from public.customer_loyalty_transactions
    where source_booking_id = new.id::text
  ) then
    update public.customers
    set loyalty_points = coalesce(loyalty_points,0) + v_points,
        loyalty_lifetime_points = coalesce(loyalty_lifetime_points,0) + v_points,
        loyalty_tier = public.crm_loyalty_tier(coalesce(loyalty_lifetime_points,0) + v_points)
    where id = new.customer_id and coalesce(is_deleted,false) = false
    returning loyalty_lifetime_points into v_lifetime;

    if found then
      insert into public.customer_loyalty_transactions(customer_id,points,transaction_type,description,source_booking_id)
      values (new.customer_id,v_points,'booking_earned','Earned from completed booking ' || new.id::text,new.id::text);
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_crm_award_booking_loyalty on public.bookings;
create trigger trg_crm_award_booking_loyalty
after insert or update of status,total_price,customer_id on public.bookings
for each row execute function public.crm_award_booking_loyalty();

revoke all on function public.crm_award_booking_loyalty() from public;

-- Existing completed bookings can be backfilled once, safely, by running:
-- insert into public.customer_loyalty_transactions ... via the same logic if desired.
