-- ============================================================
-- Translation CRM + Supabase migration
-- Public website reads translation text from public.site_translations.
-- CRM users edit translations through the existing permission system.
-- Run once in the Supabase SQL Editor.
-- ============================================================

begin;

create table if not exists public.site_translations (
  id bigint generated by default as identity primary key,
  key text not null unique,
  en text not null default '',
  ar text not null default '',
  description text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.site_translations enable row level security;

drop policy if exists site_translations_public_read on public.site_translations;
create policy site_translations_public_read
on public.site_translations
for select
to anon, authenticated
using (active = true);

drop policy if exists site_translations_crm_insert on public.site_translations;
create policy site_translations_crm_insert
on public.site_translations
for insert
to authenticated
with check (public.crm_has_permission('translations','create'));

drop policy if exists site_translations_crm_update on public.site_translations;
create policy site_translations_crm_update
on public.site_translations
for update
to authenticated
using (public.crm_has_permission('translations','update'))
with check (public.crm_has_permission('translations','update'));

drop policy if exists site_translations_crm_delete on public.site_translations;
create policy site_translations_crm_delete
on public.site_translations
for delete
to authenticated
using (public.crm_has_permission('translations','delete'));

create or replace function public.set_site_translations_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_site_translations_updated_at on public.site_translations;
create trigger trg_site_translations_updated_at
before update on public.site_translations
for each row execute function public.set_site_translations_updated_at();

-- Add Translation to the existing CRM permission catalogue.
insert into public.crm_permissions (section, action, description)
select v.section, v.action, v.description
from (values
  ('translations','read','Read website translations'),
  ('translations','create','Create translation keys'),
  ('translations','update','Edit website translations'),
  ('translations','delete','Delete translation keys')
) as v(section, action, description)
where not exists (
  select 1 from public.crm_permissions p
  where p.section = v.section and p.action = v.action
);

-- Administrators get all Translation permissions. Managers/staff keep their
-- existing role permissions unless an administrator grants Translation access.
insert into public.crm_role_permissions (role_id, permission_id)
select r.id, p.id
from public.crm_roles r
cross join public.crm_permissions p
where lower(r.name) in ('admin','administrator')
  and p.section = 'translations'
on conflict do nothing;

-- ============================================================
-- Initial migration from the existing website translation sources.
-- Re-running this block is safe: existing CRM edits are preserved.
-- ============================================================

insert into public.site_translations (key,en,ar) values ('booking.availableTimes','Available times','الأوقات المتاحة') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('booking.back','← Back to services','← العودة إلى الخدمات') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('booking.confirm','Request appointment','إرسال طلب الحجز') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('booking.continue','Continue','متابعة') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('booking.dateDescription','Pick a date, then choose a start time that fits all your selected services.','اختاري التاريخ ثم الوقت المناسب لجميع الخدمات التي اخترتها.') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('booking.dateTitle','When would you like to come?','متى ترغبين بالحضور؟') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('booking.detailsDescription','We only need a few details to confirm your appointment.','نحتاج إلى بعض البيانات فقط لتأكيد موعدك.') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('booking.detailsTitle','How can we contact you?','كيف يمكننا التواصل معك؟') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('booking.doneButton','Back to home','العودة للرئيسية') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('booking.doneDescription','Thank you. We’ll contact you to confirm your appointment.','شكراً لكِ. سنتواصل معك لتأكيد الموعد.') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('booking.doneEyebrow','ALL SET','تم') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('booking.doneTitle','Booking request received','تم استلام طلب الحجز') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('booking.edit','Edit','تعديل') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('booking.email','Email','البريد الإلكتروني') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('booking.eyebrow','YOUR APPOINTMENT','موعدك') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('booking.name','Full name','الاسم الكامل') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('booking.notes','Notes','ملاحظات') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('booking.optional','(optional)','(اختياري)') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('booking.payAtSalon','Pay at the salon','الدفع في الصالون') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('booking.payDescription','No online payment is required. We’ll contact you to confirm your appointment.','لا يلزم الدفع الإلكتروني. سنتواصل معك لتأكيد الموعد.') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('booking.phone','WhatsApp / mobile','الواتساب / الهاتف') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('booking.reference','Booking reference','رقم الحجز') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('booking.reviewDescription','Everything looks good? You can go back and change anything before confirming.','تأكدي من التفاصيل ويمكنك العودة لتعديل أي شيء قبل التأكيد.') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('booking.reviewTitle','Review your appointment','راجعي موعدك') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('booking.schedule','Your schedule','جدول موعدك') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('booking.services','Services','الخدمات') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('booking.servicesDescription','Choose one or more services. We’ll build the appointment time for you.','اختاري خدمة أو أكثر وسنرتب لكِ وقت الموعد تلقائياً.') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('booking.servicesTitle','What would you like to book?','ماذا تريدين حجزه؟') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('booking.total','Total','الإجمالي') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('categoryServices.description','Discover your perfect look with our professional women''s hair salon services. From beautiful hairstyles to advanced hair treatments, our team is here to help you look and feel your best.','اكتشفي إطلالتك المثالية مع خدمات صالون الشعر المتخصصة للنساء. من تسريحات الشعر الجميلة إلى علاجات الشعر المتقدمة، فريقنا هنا ليمنحك إطلالة تشعرين معها بأفضل حال.') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('categoryServices.title','Our Services','خدماتنا') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('common.bookNow','BOOK NOW','احجز الآن') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('common.descriptionTitle','Description','الوصف') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('common.followTitle','Follow Us','تابعنا') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('common.footerDescription','Barbershop is a No.1 place to have a men''s haircut in San Francisco. Here you can get luxury barber experience at a reasonable price.','صالون الحلاقة هو المكان الأول لقصات الشعر الرجالية في سان فرانسيسكو. هنا يمكنك الحصول على تجربة حلاقة فاخرة بسعر مناسب.') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('common.menu','Menu','القائمة') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('common.readMorebutton','Read more','اقرأ المزيد') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('common.submitButton','SEND REQUEST','إرسال الطلب') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('contactSection.description','Leave your name and phone number, and we''ll contact you.','اترك اسمك ورقم هاتفك وسنتصل بك.') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('contactSection.namePlaceholder','Full Name','الاسم الكامل') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('contactSection.phonePlaceholder','Telephone','رقم الهاتف') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('contactSection.title','Get In Touch','تواصل معنا') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('faq.empty','No frequently asked questions are available at the moment.','لا توجد أسئلة شائعة متاحة حالياً.') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('faq.error','Unable to load the FAQ right now.','تعذر تحميل الأسئلة الشائعة حالياً.') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('faq.pageTitle','Frequently Asked Questions','الأسئلة الشائعة') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('faq.pageDescription','Find answers to the most common questions about our services and bookings.','اعثري على إجابات لأكثر الأسئلة شيوعاً حول خدماتنا والحجوزات.') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('mainSection.description','Establish your new amazing look with Barbershop services! From haircuts to hot shaves, you can experience the best level of barbering in the area.','أنشئ إطلالتك الجديدة الرائعة مع خدمات الحلاقة! من قصات الشعر إلى الحلاقة الساخنة، استمتع بأعلى مستوى من الحرفية في المنطقة.') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('mainSection.title','Enjoy our barber services','استمتع بخدمات حلاقتنا') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('nav.about','About','من نحن') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('nav.contacts','Contacts','اتصل بنا') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('nav.faq','FAQ','الأسئلة الشائعة') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('nav.home','Home','الرئيسية') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('nav.hours','Opening Hours','ساعات العمل') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('nav.langSwitcherLabel','العربية','English') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('nav.services','Services','الخدمات') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('nav.vouchers','Vouchers','قسائم') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('openingHours.days.label-1','Monday – Friday','الاثنين – الجمعة') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('openingHours.days.label-2','Saturday and Sunday','السبت والأحد') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('openingHours.title','Opening Hours','ساعات العمل') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('ourServices.description','Barbershop offers world-class men''s haircuts, beard grooming, and hot razor shaves. Here are just some of the services we are famous for.','يقدم صالون الحلاقة قصات شعر رجالية عالمية المستوى، وتهذيب اللحية، والحلاقة بالموس الساخن. إليك بعض الخدمات التي نشتهر بها.') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('ourServices.items.0.description','Modern cuts and styling tailored for women','قصات وتسريحات عصرية مخصصة للسيدات') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('ourServices.items.0.title','Hair Styles','تسريحات الشعر') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('ourServices.items.1.description','Professional treatments to nourish and repair hair','علاجات احترافية لتغذية الشعر وإصلاحه') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('ourServices.items.1.title','Hair Treatments','علاجات الشعر') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('ourServices.title','OUR SERVICES','خدماتنا') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('servicesPage.book','Book','احجز') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('servicesPage.bookNow','Book Now','احجز الآن') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('voucher.description','Choose a voucher and redeem it on the corresponding service.','اختر قسيمة واستخدمها في الخدمة المناسبة.') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('voucher.title','Vouchers','قسائم') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('whoWeAre.description','Barbershop is a team of highly qualified barbers dedicated to offering the best value. We do this by providing high quality salon services for men and boys, in a warm, friendly atmosphere.','صالون الحلاقة هو فريق من الحلاقين المؤهلين تأهيلاً عالياً، ملتزمون بتقديم أفضل قيمة. نحقق ذلك من خلال تقديم خدمات صالون عالية الجودة للرجال والأولاد في أجواء دافئة وودية.') on conflict (key) do nothing;
insert into public.site_translations (key,en,ar) values ('whoWeAre.title','WHO WE ARE','من نحن') on conflict (key) do nothing;

commit;

-- Verify:
-- select key,en,ar from public.site_translations order by key;
-- select p.section,p.action,r.name
-- from public.crm_permissions p
-- left join public.crm_role_permissions rp on rp.permission_id=p.id
-- left join public.crm_roles r on r.id=rp.role_id
-- where p.section='translations'
-- order by p.action,r.name;
