-- JAS Premium: Permanent URL QR Codes
-- The QR stores only the stable resolver URL + permanent_code.
-- Changing destination_url never changes the printed QR code.

create table if not exists public.url_qr_codes (
  id bigint generated by default as identity primary key,
  permanent_code text not null unique,
  name text not null,
  destination_url text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint url_qr_codes_destination_https check (destination_url ~* '^https?://')
);

create or replace function public.url_qr_codes_set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_url_qr_codes_updated_at on public.url_qr_codes;
create trigger trg_url_qr_codes_updated_at
before update on public.url_qr_codes
for each row execute function public.url_qr_codes_set_updated_at();

alter table public.url_qr_codes enable row level security;

drop policy if exists url_qr_codes_read on public.url_qr_codes;
create policy url_qr_codes_read on public.url_qr_codes
for select to authenticated
using (public.crm_has_permission('url-qr-codes','read'));

drop policy if exists url_qr_codes_create on public.url_qr_codes;
create policy url_qr_codes_create on public.url_qr_codes
for insert to authenticated
with check (public.crm_has_permission('url-qr-codes','create'));

drop policy if exists url_qr_codes_update on public.url_qr_codes;
create policy url_qr_codes_update on public.url_qr_codes
for update to authenticated
using (public.crm_has_permission('url-qr-codes','update'))
with check (public.crm_has_permission('url-qr-codes','update'));

-- Deliberately no DELETE policy. A printed QR must remain resolvable forever.

create or replace function public.get_public_url_qr_destination(p_code text)
returns text
language sql
security definer
set search_path = public
as $$
  select destination_url
  from public.url_qr_codes
  where permanent_code = p_code
  limit 1;
$$;

grant execute on function public.get_public_url_qr_destination(text) to anon, authenticated;

-- Add the section to the CRM permission catalogue if the catalogue exists.
insert into public.crm_permissions (section, action)
select 'url-qr-codes', a.action
from (values ('read'),('create'),('update')) as a(action)
where not exists (
  select 1 from public.crm_permissions p where p.section='url-qr-codes' and p.action=a.action
);

-- Give administrators the section if role permission tables are present.
insert into public.crm_role_permissions (role_id, permission_id)
select r.id, p.id
from public.crm_roles r
cross join public.crm_permissions p
where lower(r.name) in ('admin','administrator')
  and p.section='url-qr-codes'
  and not exists (
    select 1 from public.crm_role_permissions rp where rp.role_id=r.id and rp.permission_id=p.id
  );

-- If the finance audit table/function has already been installed, audit QR changes too.
drop trigger if exists finance_audit_url_qr_codes on public.url_qr_codes;
create trigger finance_audit_url_qr_codes
after insert or update or delete on public.url_qr_codes
for each row execute function public.finance_audit_trigger();
