-- ============================================================
-- Voucher catalogue + image storage
-- Run this once in Supabase SQL Editor.
-- ============================================================

create table if not exists public.vouchers (
  id bigint generated by default as identity primary key,
  sku text not null unique,
  title_en text not null,
  title_ar text,
  active boolean not null default true,
  sort_order integer not null default 0,
  duration_minutes integer not null default 30 check (duration_minutes > 0),
  price_usd numeric(10,2),
  price_qar numeric(10,2),
  image_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- If a vouchers table already existed, add the new source-of-truth fields
-- without destroying existing data.
alter table public.vouchers add column if not exists sku text;
alter table public.vouchers add column if not exists title_en text;
alter table public.vouchers add column if not exists title_ar text;
alter table public.vouchers add column if not exists active boolean not null default true;
alter table public.vouchers add column if not exists sort_order integer not null default 0;
alter table public.vouchers add column if not exists duration_minutes integer not null default 30;
alter table public.vouchers add column if not exists price_usd numeric(10,2);
alter table public.vouchers add column if not exists price_qar numeric(10,2);
alter table public.vouchers add column if not exists image_path text;
alter table public.vouchers add column if not exists created_at timestamptz not null default now();
alter table public.vouchers add column if not exists updated_at timestamptz not null default now();

-- Migrate common legacy voucher columns when they exist.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema='public' and table_name='vouchers' and column_name='title'
  ) then
    execute $sql$
      update public.vouchers
      set title_en = coalesce(nullif(title_en,''), title)
      where nullif(title,'') is not null
    $sql$;
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema='public' and table_name='vouchers' and column_name='image'
  ) then
    execute $sql$
      update public.vouchers
      set image_path = coalesce(nullif(image_path,''), image)
      where nullif(image,'') is not null
    $sql$;
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema='public' and table_name='vouchers' and column_name='durationMinutes'
  ) then
    execute $sql$
      update public.vouchers
      set duration_minutes = case
        when duration_minutes is null or duration_minutes = 30
          then coalesce("durationMinutes", duration_minutes, 30)
        else duration_minutes
      end
    $sql$;
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema='public' and table_name='vouchers' and column_name='price'
  ) then
    execute $sql$
      update public.vouchers
      set price_usd = coalesce(price_usd, price)
    $sql$;
  end if;
end $$;

-- Legacy columns are no longer used by the application. Older versions of
-- the vouchers table may contain required fields such as name_en/name_ar,
-- descriptions, discount fields, dates, etc. The new CRM source of truth is
-- the canonical fields above, so legacy fields must not block inserts/updates.
--
-- First copy useful legacy names into the canonical title fields where those
-- legacy columns exist.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema='public' and table_name='vouchers' and column_name='name_en'
  ) then
    execute $sql$
      update public.vouchers
      set title_en = coalesce(nullif(title_en,''), nullif(name_en,''))
      where nullif(name_en,'') is not null
    $sql$;
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema='public' and table_name='vouchers' and column_name='name_ar'
  ) then
    execute $sql$
      update public.vouchers
      set title_ar = coalesce(nullif(title_ar,''), nullif(name_ar,''))
      where nullif(name_ar,'') is not null
    $sql$;
  end if;
end $$;

-- Drop NOT NULL only from legacy columns. Keep the canonical source-of-truth
-- columns protected by their intended constraints. This makes the migration
-- safe even when the existing vouchers table has a different legacy schema.
do $$
declare
  col record;
begin
  for col in
    select column_name
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'vouchers'
      and is_nullable = 'NO'
      and column_name not in (
        'id',
        'sku',
        'title_en',
        'title_ar',
        'active',
        'sort_order',
        'duration_minutes',
        'created_at',
        'updated_at'
      )
  loop
    execute format(
      'alter table public.vouchers alter column %I drop not null',
      col.column_name
    );
  end loop;
end $$;

-- Safe defaults for any rows created by an older schema.
update public.vouchers
set
  sku = coalesce(nullif(sku,''), 'V-' || lpad(id::text, 3, '0')),
  title_en = coalesce(nullif(title_en,''), 'Voucher'),
  duration_minutes = coalesce(duration_minutes, 30),
  active = coalesce(active, true),
  sort_order = coalesce(sort_order, 0),
  updated_at = now();

create unique index if not exists vouchers_sku_unique on public.vouchers(sku);
create index if not exists vouchers_active_sort_idx
  on public.vouchers(active, sort_order, created_at desc);

-- Updated timestamp.
create or replace function public.set_voucher_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_vouchers_updated_at on public.vouchers;
create trigger trg_vouchers_updated_at
before update on public.vouchers
for each row execute function public.set_voucher_updated_at();

-- ============================================================
-- RLS
-- ============================================================
alter table public.vouchers enable row level security;

drop policy if exists "public_select_active_vouchers" on public.vouchers;
create policy "public_select_active_vouchers"
on public.vouchers
for select
to anon, authenticated
using (active = true);

drop policy if exists "crm_admin_select_vouchers" on public.vouchers;
create policy "crm_admin_select_vouchers"
on public.vouchers
for select
to authenticated
using ((select public.is_admin()));

drop policy if exists "crm_admin_insert_vouchers" on public.vouchers;
create policy "crm_admin_insert_vouchers"
on public.vouchers
for insert
to authenticated
with check ((select public.is_admin()));

drop policy if exists "crm_admin_update_vouchers" on public.vouchers;
create policy "crm_admin_update_vouchers"
on public.vouchers
for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "crm_admin_delete_vouchers" on public.vouchers;
create policy "crm_admin_delete_vouchers"
on public.vouchers
for delete
to authenticated
using ((select public.is_admin()));

-- ============================================================
-- Public Supabase Storage bucket for voucher images
-- ============================================================
insert into storage.buckets (id, name, public)
values ('vouchers', 'vouchers', true)
on conflict (id) do update set public = true;

drop policy if exists "crm_admin_upload_voucher_images" on storage.objects;
create policy "crm_admin_upload_voucher_images"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'vouchers'
  and (select public.is_admin())
);

drop policy if exists "crm_admin_update_voucher_images" on storage.objects;
create policy "crm_admin_update_voucher_images"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'vouchers'
  and (select public.is_admin())
)
with check (
  bucket_id = 'vouchers'
  and (select public.is_admin())
);

drop policy if exists "crm_admin_delete_voucher_images" on storage.objects;
create policy "crm_admin_delete_voucher_images"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'vouchers'
  and (select public.is_admin())
);

-- The bucket is public, so website visitors can display image URLs returned
-- by getPublicUrl() without an authenticated Storage session.

-- ============================================================
-- Seed the four existing voucher records.
-- Images are intentionally left empty: upload the existing images once
-- through CRM -> Vouchers -> Edit/Upload image.
-- ============================================================
insert into public.vouchers
  (sku, title_en, title_ar, active, sort_order, duration_minutes, price_usd, price_qar)
values
  ('V-001','Voucher 1','قسيمة 1',true,1,30,null,null),
  ('V-002','Voucher 2','قسيمة 2',true,2,30,null,null),
  ('V-003','Voucher 3','قسيمة 3',true,3,30,null,null),
  ('V-004','Voucher 4','قسيمة 4',true,4,30,null,null)
on conflict (sku) do nothing;

-- Verify:
-- select id, sku, title_en, active, duration_minutes, price_usd, price_qar, image_path
-- from public.vouchers
-- order by id desc;
